"""Add Profession model

Revision ID: 4ea7d3ef73c1
Revises: 5ef13c093778
Create Date: 2025-04-10 11:16:19.599971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea7d3ef73c1'
down_revision = '5ef13c093778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=False),
    sa.Column('fee_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professions')
    # ### end Alembic commands ###
