"""Add registration_validated field

Revision ID: 5407d4fe2307
Revises: f098914f8808
Create Date: 2025-04-13 08:18:13.691864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5407d4fe2307'
down_revision = 'f098914f8808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_validated', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.drop_column('registration_validated')

    # ### end Alembic commands ###
