"""Add terms_and_conditions to AppSettings

Revision ID: 832e00817103
Revises: aaacbce99e2a
Create Date: 2025-04-10 17:17:53.989232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832e00817103'
down_revision = 'aaacbce99e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_and_conditions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('terms_and_conditions')

    # ### end Alembic commands ###
