"""Add Course_Registration model

Revision ID: aaacbce99e2a
Revises: a8f22e8ebbc4
Create Date: 2025-04-10 12:23:33.192001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaacbce99e2a'
down_revision = 'a8f22e8ebbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscription_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name_ar', sa.String(length=100), nullable=False),
    sa.Column('last_name_ar', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_state_id', sa.Integer(), nullable=False),
    sa.Column('birth_municipality_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_level_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_fee_value', sa.Float(), nullable=False),
    sa.Column('registration_terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['birth_municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['birth_state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['course_level_id'], ['course_levels.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inscription_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_registrations')
    # ### end Alembic commands ###
